# Generated by Django 4.1.4 on 2022-12-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar',
            name='pagetitle',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
