# Generated by Django 4.1.4 on 2022-12-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite_app', '0002_navbar_pagetitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbar',
            name='navlogo',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
