# Generated by Django 4.1.4 on 2022-12-27 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite_app', '0003_alter_navbar_navlogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_sm_img', models.ImageField(blank=True, null=True, upload_to='media/h_sm_img')),
                ('home_lg_img', models.ImageField(blank=True, null=True, upload_to='media/h_lg_img')),
                ('sec_heading', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
