# Generated by Django 4.1.4 on 2022-12-27 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite_app', '0004_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('illustration_img', models.ImageField(blank=True, null=True, upload_to='media/illustration')),
                ('my_dp', models.ImageField(blank=True, null=True, upload_to='media/my_DP')),
                ('little_desc', models.TextField(blank=True, max_length=500, null=True)),
                ('upload_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='home',
            name='upload_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
