# Generated by Django 4.1.4 on 2022-12-28 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite_app', '0005_about_home_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='little_desc',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
