# Generated by Django 4.1.4 on 2023-01-01 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite_app', '0009_project_project_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_pic', models.ImageField(null=True, upload_to='media/web_pic')),
                ('web_name', models.CharField(max_length=265, null=True)),
                ('web_desc', models.TextField()),
                ('web_url', models.URLField(max_length=500)),
                ('web_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite_app.webtype')),
            ],
        ),
    ]
